In [1]:
import numpy as np

# Set seed for reproducibility
np.random.seed(42)

# Generate Matrix A (4x3) and Matrix B (3x5) with integers in [1, 10]
A = np.random.randint(1, 11, size=(4, 3))
B = np.random.randint(1, 11, size=(3, 5))

print("=== Matrix A ===")
print(A)
print("Matrix A Shape:", A.shape)

print("\n=== Matrix B ===")
print(B)
print("Matrix B Shape:", B.shape)

=== Matrix A ===
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]]
Matrix A Shape: (4, 3)

=== Matrix B ===
[[ 8  3  6  5  2]
 [ 8  6  2  5  1]
 [10  6  9  1 10]]
Matrix B Shape: (3, 5)


In [2]:
# Programmatically validate inner dimensions match
assert A.shape[1] == B.shape[0], f"Inner dimensions do not match: {A.shape[1]} != {B.shape[0]}"

# Compute matrix product
C = np.dot(A, B)

print("=== Matrix C (A . B) ===")
print(C)
print("Matrix C Shape:", C.shape)

# Verify shape is (4, 5)
assert C.shape == (4, 5), f"Expected shape (4, 5), but got {C.shape}"
print("Shape validation successful: C has shape (4, 5)")

=== Matrix C (A . B) ===
[[168  93 122  63  98]
 [196 117 134  70 117]
 [160  99 104  58  93]
 [152  87 110  53  94]]
Matrix C Shape: (4, 5)
Shape validation successful: C has shape (4, 5)


In [3]:
# Total sum of all elements in C
total_sum = np.sum(C)
print(f"Total Sum of all elements in C: {total_sum}")

# Row-wise sums (axis=1)
row_sums = np.sum(C, axis=1)
print(f"Row-wise sums (axis=1): {row_sums}")

# Column-wise sums (axis=0)
col_sums = np.sum(C, axis=0)
print(f"Column-wise sums (axis=0): {col_sums}")


Total Sum of all elements in C: 2188
Row-wise sums (axis=1): [544 634 514 496]
Column-wise sums (axis=0): [676 396 470 244 402]
